# -*- coding: utf-8 -*-
"""Edubridge_Fraud_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MpYlJvLGlMwttTkCiN6L0Gln4TJAKskv

**Fraud Detection**
"""

import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.preprocessing import LabelEncoder

# Train Test Split
from sklearn.model_selection import train_test_split

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# Evaluation
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

# loading dataset

df = pd.read_csv("/content/fraud_detection_dataset.csv")

"""**Data Exploration**"""

df.info()

df

df.describe()

df.isnull().sum()

"""**Drop Unnecessary Column**"""

df.drop("TransactionID", axis=1, inplace=True)

df

"""**Encode Categorical Values**"""

# le = LabelEncoder()

# df['Location'] = le.fit_transform(df['Location'])

# df['Merchant'] = le.fit_transform(df['Merchant'])

# df['DeviceType'] = le.fit_transform(df['DeviceType'])

df = pd.get_dummies(df, drop_first=True)

df.head(20)

"""**Define Features and Target**"""

x = df.drop('Fraud', axis=1)

y = df['Fraud']

y

"""**Train - Test Split**"""

x_train, x_test, y_train, y_test = train_test_split(
    x,y,
    random_state= 42,
    test_size= 0.2
)

"""**Logistic Regression Model**"""

# we need Standard Scaler to equalize the values for different cols
# we need to standardise values/data for cols when we r using Logistic Regression
from sklearn.preprocessing import StandardScaler

"""Main Reasons
1. Features are on very different scales

Example:

Time → 0 to 23

Amount → 1000 to 90000

Large differences slow convergence.
"""

#Scaling our x_train and x_test

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)

x_test = scaler.transform(x_test)

lr_model = LogisticRegression(max_iter= 1000) # increasing iterations

lr_model.fit(x_train, y_train)

y_pred_lr = lr_model.predict(x_test)

print(y_pred_lr)

"""**Evaluate Logistic Regression**"""

print("Logistic Regression Accuracy : ",
      accuracy_score(y_test, y_pred_lr))
print()

print("Classification report : ",
      classification_report(y_test, y_pred_lr))
print()

print("Confusion Matrix : ",
      confusion_matrix(y_test, y_pred_lr))

"""**Random Forest**"""

rf_model = RandomForestClassifier(
    n_estimators = 100,
    class_weight='balanced',
    random_state = 42
)

rf_model.fit(x_train, y_train)

y_pred_rf = rf_model.predict(x_test)

print(y_pred_rf)

"""**Evaluate Random Forest**"""

print("Random Forest Accuracy : ",
      accuracy_score(y_test, y_pred_rf))
print()

print("Classification Report : ",
      classification_report(y_test, y_pred_rf))
print()

print("Confusion Matrix : ",
      confusion_matrix(y_test, y_pred_rf))

"""**Compare Both Models**

Precision → How many predicted frauds were actually frauds

Recall → How many actual frauds were detected
"""

comparison = pd.DataFrame({
    "Model": ["Logistic Regression", "Random Forest"],
    "Accuracy": [
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_rf)
    ],
    "Precision": [
        precision_score(y_test, y_pred_lr),
        precision_score(y_test, y_pred_rf)
    ],
    "Recall": [
        recall_score(y_test, y_pred_lr),
        recall_score(y_test, y_pred_rf)
    ],
    "F1 Score": [
        f1_score(y_test, y_pred_lr),
        f1_score(y_test, y_pred_rf)
    ]
})

print(comparison)

"""**Fraud Distribution**"""

print(df['Fraud'].value_counts())

sns.countplot(x="Fraud", data=df)
plt.show()

sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.show()

