# -*- coding: utf-8 -*-
"""Edubridge_House pricing Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RSkbkdF4X22zVIpQjMBlxS4yiFW6n9or

**House Pricing Detection**
"""

import numpy as np
import pandas as pd

# Visualization:
#----------------
import matplotlib.pyplot as plt
import seaborn as sns

#Preprocessing:
#--------------
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Models:
#--------
from sklearn.linear_model import LinearRegression

#Evaluation:
#-----------
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

#Load DataSet
df = pd.read_csv("/content/house_prices.csv")

"""**Data Exploration**"""

df.info()

df.head()

df.describe()

df.isnull().sum()

"""**Drop Unnecessary Column**"""

df.drop("HouseID", axis=1, inplace=True)

"""**Encode Categorical Data**"""

le = LabelEncoder()

df['Location'] = le.fit_transform(df['Location'])

df.head(20)

"""**Defining Features and Target**"""

x = df.drop('Price', axis = 1) # in x-axis we r removing price col

y = df['Price']  # in y-axis we r adding Price col, cuz its our target

"""**Train-Test Split**

80% - Training

20% - Testing
"""

x_test, x_train, y_test, y_train = train_test_split(
    x,y,
    test_size = 0.2,
    random_state = 42
)

"""**Train Model**"""

model = LinearRegression()

model.fit(x_train, y_train)

"""**Make Predictions**"""

y_pred = model.predict(x_test)
print(y_pred)

"""**Evaluate using : MAE, RMSE, r^2**"""

# MAE (mean absolute error)

mae = mean_absolute_error(y_test, y_pred)
print(mae)

# RMSE (Root Mean Square Error)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("RMSE:", rmse)

# r2 score

r2 = r2_score(y_test, y_pred)

print("R2 Score:", r2)

"""**Visualization**"""

plt.figure(figsize = (8,5))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")

plt.title("Actual vs Predicted Prices")

plt.show()

"""**Predict New House Prices**"""

new_house = [[2,3,2,1800]]  #[Location, Bedrooms, Bathrooms, SquareFeet]

prediction = model.predict(new_house)

print("Predicted new house price : ",prediction)

